import {StyleSheet,Dimensions} from 'react-native'

export default StyleSheet.create({
    container:{
        flex:1,
        padding:10,
        backgroundColor:'white'
        
    },
    image:{
        margin:5,
        height: Dimensions.get("window").height/2,
        resizeMode:'contain',
    },
    title:{
        fontWeight:'bold',
        color:'black',
        fontSize:19,
    },
    infoContainer:{
        flexDirection:'row'
    },
    rate:{
        fontSize:17,
        fontWeight:"800",
        marginRight:5
    },
    count:{
        fontSize:17,
        fontWeight:"800",
        color:'grey'
    },
    buttonContainer:{
        borderTopWidth:1,
        flexDirection:'row',
        marginBottom:5,
        padding:5,
        borderColor:'gray',
        alignItems:'center'
    },
    button:{
        flex:0.7,
        backgroundColor:'#cc6600',
        borderRadius:5,
        padding:10
    },
    buttonText:{
        color:'white',
        textAlign:'center',
        fontSize:17,
        fontWeight:'900'
    },
    productDescriptionTitle:{
        color:'black',
        fontSize:19,
        fontWeight:'bold',
        marginTop:10
    },
    description:{
        color:'grey',
        fontWeight:'600',
        marginTop:3,
        marginBottom:10
    },
    priceContainer:{
        flex:0.4,
        marginRight:15,
    },
    price:{
        fontWeight:'bold',
        fontSize:19,
        color:'#cc6600',
        textAlign:'center'
    },
    discountInfo:{
        fontWeight:'bold',
        color:'#2b2b2b',
        textAlign:'center'
    }
})